export { default as About } from './About'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as Portfolio } from './HowWorks'
export { default as Faq } from './Faq'